---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _includes/pages
  label: Pages (INCLUDES)
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: pages
  label: Pages (PAGES)
  create: all
  match: "**/*"
  new_doc_ext: html
- type: jekyll-posts
  label: News
  create: all
- type: directory
  path: _data
  label: Fichiers de données
  create: documents
  match: "**/*"
  new_doc_ext: yml
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
