backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "News"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Menu", name: "menu", widget: "hidden", default: "cfs"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Banner", name: "banner", widget: image, required: false}
      - {label: "Infos complémentaires", name: "infos", widget: "object", collapsed: true, fields: [
          {label: "Publier la news ?", name: "online", widget: "boolean", required: false},
          {label: "Date", name: "date", widget: "datetime", required: false},
          {label: "Teaser", name: "teaser", widget: "string", required: false}
          ]
        }
      - {label: "Texte de la news", name: "content", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: string, required: false}
      - {label: "Permalink si nécessaire", name: "permalink", widget: "string"}
      - {label: "SEO, référencement et réseaux sociaux", name: "seo", widget: "object", collapsed: true, fields: [
          {label: "Description", name: "og_description", widget: "text"},
          {label: "Mots clés pour les moteurs de recherche", name: "keywords", widget: "text"},
          {label: "Image pour les réseaux sociaux", name: "og_img", widget: "image"},
          {label: "Type de contenu", name: "og_type", widget: "select", options: ["article", "video", "website"], default: ["website"]}
          ]
        }
  - name: "autres-pages"
    label: "Autres pages"
    folder: "pages"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "index"}
      - {label: "Menu", name: "menu", widget: "hidden", default: "cfs"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Banner", name: "banner", widget: image, required: false}
      - {label: "Texte", name: "text", widget: markdown, required: false}
      - {label: "SEO, référencement et réseaux sociaux", name: "seo", widget: "object", collapsed: true, fields: [
          {label: "Description", name: "og_description", widget: "text"},
          {label: "Mots clés pour les moteurs de recherche", name: "keywords", widget: "text"},
          {label: "Image pour les réseaux sociaux", name: "og_img", widget: "image"},
          {label: "Type de contenu", name: "og_type", widget: "select", options: ["article", "video", "website"], default: ["website"]}
          ]
        }
        
  - name: "pages"
    label: "Pages"
    files:
      - file: "pages/stages_enfants/index.html"
        label: "Stages Enfants"
        name: "index"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "index"}
          - {label: "Menu", name: "menu", widget: "hidden", default: "cfs"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: image, required: false}
          - {label: "Introduction", name: "intro", widget: markdown, required: false}
          - {label: "Périodes de stages", name: "periodes", widget: object, collapsed: true, fields: [
              {label: "Carnaval", name: "carnaval", widget: "object", collapsed: true, fields: [
                {label: "Afficher sur le site ?", name: "online", widget: "boolean"},
                {label: Villes, name: lieu, widget: list, fields: [
                  {label: "Disponible ?", name: "dispo", widget: "boolean", default: true},
                  {label: "Nom", name: "name", widget: select, options: ["Bruxelles", "Brabant Wallon", "Liège", "Stages en internat"]},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Lien", name: "link", widget: "string"},
                  {label: "Texte du bouton", name: "button_text", widget: "string", required: false},
                  {label: "Couleur du bouton", name: "button_color", widget: "string", required: false}
                  ]
                }
                ]
              },
              {label: "Pâques", name: "paques", widget: "object", collapsed: true, fields: [
                {label: "Afficher sur le site ?", name: "online", widget: "boolean"},
                {label: Villes, name: lieu, widget: list, fields: [
                  {label: "Disponible ?", name: "dispo", widget: "boolean", default: true},
                  {label: "Nom", name: "name", widget: select, options: ["Bruxelles", "Brabant Wallon", "Liège", "Stages en internat"]},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Lien", name: "link", widget: "string"},
                  {label: "Texte du bouton", name: "button_text", widget: "string", required: false},
                  {label: "Couleur du bouton", name: "button_color", widget: "string", required: false}
                  ]
                }
                ]
              },
              {label: "Été", name: "ete", widget: "object", collapsed: true, fields: [
                {label: "Afficher sur le site ?", name: "online", widget: "boolean"},
                {label: Villes, name: lieu, widget: list, fields: [
                  {label: "Disponible ?", name: "dispo", widget: "boolean", default: true},
                  {label: "Nom", name: "name", widget: select, options: ["Bruxelles", "Brabant Wallon", "Liège", "Stages en internat"]},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Lien", name: "link", widget: "string"},
                  {label: "Texte du bouton", name: "button_text", widget: "string", required: false},
                  {label: "Couleur du bouton", name: "button_color", widget: "string", required: false}
                  ]
                }
                ]
              },
              {label: "Toussaint", name: "toussaint", widget: "object", collapsed: true, fields: [
                {label: "Afficher sur le site ?", name: "online", widget: "boolean"},
                {label: Villes, name: lieu, widget: list, fields: [
                  {label: "Disponible ?", name: "dispo", widget: "boolean", default: true},
                  {label: "Nom", name: "name", widget: select, options: ["Bruxelles", "Brabant Wallon", "Liège", "Stages en internat"]},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Lien", name: "link", widget: "string"},
                  {label: "Texte du bouton", name: "button_text", widget: "string", required: false},
                  {label: "Couleur du bouton", name: "button_color", widget: "string", required: false}
                  ]
                }
                ]
              },
              {label: "Noël", name: "noel", widget: "object", collapsed: true, fields: [
                {label: "Afficher sur le site ?", name: "online", widget: "boolean"},
                {label: Villes, name: lieu, widget: list, fields: [
                  {label: "Disponible ?", name: "dispo", widget: "boolean", default: true},
                  {label: "Nom", name: "name", widget: select, options: ["Bruxelles", "Brabant Wallon", "Liège", "Stages en internat"]},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Lien", name: "link", widget: "string"},
                  {label: "Texte du bouton", name: "button_text", widget: "string", required: false},
                  {label: "Couleur du bouton", name: "button_color", widget: "string", required: false}
                  ]
                }
                ]
              },
              {label: "Nouvel an", name: "nouvel_an", widget: "object", collapsed: true, fields: [
                {label: "Afficher sur le site ?", name: "online", widget: "boolean"},
                {label: Villes, name: lieu, widget: list, fields: [
                  {label: "Disponible ?", name: "dispo", widget: "boolean", default: true},
                  {label: "Nom", name: "name", widget: select, options: ["Bruxelles", "Brabant Wallon", "Liège", "Stages en internat"]},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Lien", name: "link", widget: "string"},
                  {label: "Texte du bouton", name: "button_text", widget: "string", required: false},
                  {label: "Couleur du bouton", name: "button_color", widget: "string", required: false}
                  ]
                }
                ]
              }
              ]
            }
          - {label: "SEO, référencement et réseaux sociaux", name: "seo", widget: "object", collapsed: true, fields: [
              {label: "Description", name: "og_description", widget: "text"},
              {label: "Mots clés pour les moteurs de recherche", name: "keywords", widget: "text"},
              {label: "Image pour les réseaux sociaux", name: "og_img", widget: "image"},
              {label: "Type de contenu", name: "og_type", widget: "select", options: ["article", "video", "website"], default: ["website"]}
              ]
            }
  - name: "data"
    label: "Data"
    files: 
      - file: "_data/stages.yml"
        name: stages
        label: "Liste des stages"  
        fields:
          - {label: Liste des stages, name: stages, widget: list, fields: [
              {label: Nom, name: name, widget: string},
              {label: Image, name: image, widget: image},
              {label: Lieux de stage, name: lieux, widget: list, fields: [
                {label: Ville, name: city, widget: select, options: ["Bruxelles", "Brabant Wallon", "Liège"]},
                {label: Description, name: description, widget: markdown},
                {label: Âge, name: age, widget: string},
                {label: Informations complémentaires, name: infos, widget: string, required: false}
              ]
              },
              {label: Catégorie, name: category, widget: select, options: [
                {label: "Les petits bouts", value: "bouts"},
                {label: "Découvertes sportives et culturelles", value: "decouvertes"},
                {label: "Danse et Gymnastique", value: "danse"},
                {label: "Activités sportives", value: "sportives"},
                {label: "Activités Fun", value: "fun"},
                {label: "Activités artistiques et culturelles", value: "artistiques"}
              ]
              },
              {label: Stage à publier ?, name: online, widget: boolean, required: false},
              {label: Nouveau stage ?, name: new, widget: boolean, required: false},
              {label: Stage à mettre à la une ?, name: stage_une, widget: boolean, required: false}
              ]
            }
      - file: "_data/centres_cfs.yml"
        name: centres_cfs
        label: "Liste des centres CFS"  
        fields:
          - {label: Liste des centres, name: centres, widget: list, fields: [
              {label: Nom, name: name, widget: string},
              {label: Image, name: image, widget: image},
                {label: Adresse, name: adresse, widget: object, fields: [
                  {label: Rue et numéro, name: rue, widget: string},
                  {label: Code postal, name: code_postal, widget: number},
                  {label: Ville, name: ville, widget: string},
                  {label: Pays, name: pays, widget: string, required: false}
                  ]
                },
                {label: Carte, name: map, widget: map, required: false}
              ]
            }
